pipeline:
  build:
    image: node
    commands:
      - cd frontend
      - npm i redis --save
      - npm test
  publish:
    image: plugins/docker
    repo: dstrebel/node-drone
    secrets: [ docker_username, docker_password ]