# Drone Pipeline
pipeline:
  build:
    image: node
    commands:
      - cd frontend
      - npm i redis --save
      - npm test
  publish:
    image: plugins/docker
    repo: dstrebel/frontend
    tags: [latest, v2]
    secrets: [ docker_username, docker_password ]
  kubectl:
    image: komljen/drone-kubectl-helm
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    kubectl: "apply -f ./frontend/deployment.yaml"