pipeline:
  build:
    image: node
    commands:
      - npm i redis --save ./frontend
      - npm test ./frontend
  publish:
    image: plugins/docker
    repo: dstrebel/node-drone
    secrets: [ docker_username, docker_password ]