# Drone Pipeline
pipeline:
  build:
    image: node
    commands:
      - cd frontend
      - npm i redis --save
      - npm test
  publish:
    image: plugins/docker
    repo: dstrebel/frontend-drone
    tags: [latest, v2]
    secrets: [ docker_user, docker_password ]
  kubectl:
    image: lachlanevenson/k8s-kubectl
    secrets: [ kube_server, kube_ca, kube_token ]
    kubectl: "apply -f ./frontend/deployment.yaml"
